/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Maincraft(props) {
  const myMesh = React.useRef();
  useFrame(({ clock }) => {
    const a = Math.PI * 0.07 * clock.getElapsedTime();
    myMesh.current.rotation.y = a;
  });
  const { nodes, materials } = useGLTF("/models/const.gltf");
  return (
    <group {...props} dispose={null} ref={myMesh}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="column_under_wood_base_0"
            castShadow
            receiveShadow
            geometry={nodes.column_under_wood_base_0.geometry}
            material={materials.wood_base}
          />
          <mesh
            name="barrel_metal_0"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            name="barrel_metal_dop_0"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_dop_0.geometry}
            material={materials.metal_dop}
          />
          <mesh
            name="barrel_barrel16_0"
            castShadow
            receiveShadow
            geometry={nodes.barrel_barrel16_0.geometry}
            material={materials.barrel16}
          />
          <mesh
            name="boxes_boxes211_0"
            castShadow
            receiveShadow
            geometry={nodes.boxes_boxes211_0.geometry}
            material={materials.boxes211}
          />
          <mesh
            name="boxes_barrel16_0"
            castShadow
            receiveShadow
            geometry={nodes.boxes_barrel16_0.geometry}
            material={materials.barrel16}
          />
          <mesh
            name="rocks_down_lambert17_0"
            castShadow
            receiveShadow
            geometry={nodes.rocks_down_lambert17_0.geometry}
            material={materials.lambert17}
          />
          <mesh
            name="grass1_grass_0"
            castShadow
            receiveShadow
            geometry={nodes.grass1_grass_0.geometry}
            material={materials.grass}
          />
          <mesh
            name="grass1_grass_0001"
            castShadow
            receiveShadow
            geometry={nodes.grass1_grass_0001.geometry}
            material={materials.grass}
          />
          <mesh
            name="grass1_grass_0002"
            castShadow
            receiveShadow
            geometry={nodes.grass1_grass_0002.geometry}
            material={materials.grass}
          />
          <mesh
            name="grass1_grass_0003"
            castShadow
            receiveShadow
            geometry={nodes.grass1_grass_0003.geometry}
            material={materials.grass}
          />
        </group>
      </group>
      <mesh
        name="base_under_albedo_0"
        castShadow
        receiveShadow
        geometry={nodes.base_under_albedo_0.geometry}
        material={materials.albedo}
      />
      <mesh
        name="base_under_grass_base_0"
        castShadow
        receiveShadow
        geometry={nodes.base_under_grass_base_0.geometry}
        material={materials.grass_base}
      />
      <mesh
        name="base_under_stone_down_0"
        castShadow
        receiveShadow
        geometry={nodes.base_under_stone_down_0.geometry}
        material={materials.stone_down}
      />
      <group name="Sketchfab_model001" rotation={[-Math.PI / 2, 0, 0]}>
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx001"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="barrel_metal_0001"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_0001.geometry}
            material={materials["metal.001"]}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model002"
        position={[-9.33, 0, 8.52]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx002"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="barrel_metal_0002"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_0002.geometry}
            material={materials["metal.002"]}
          />
          <mesh
            name="barrel_barrel16_0001"
            castShadow
            receiveShadow
            geometry={nodes.barrel_barrel16_0001.geometry}
            material={materials["barrel16.001"]}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model003"
        position={[-9.09, 0, 7.25]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx003"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="barrel_metal_0003"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_0003.geometry}
            material={materials["metal.003"]}
          />
          <mesh
            name="barrel_barrel16_0002"
            castShadow
            receiveShadow
            geometry={nodes.barrel_barrel16_0002.geometry}
            material={materials["barrel16.002"]}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model004"
        position={[-8.03, 0, 8.21]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx004"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="barrel_metal_0004"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_0004.geometry}
            material={materials["metal.004"]}
          />
          <mesh
            name="barrel_barrel16_0003"
            castShadow
            receiveShadow
            geometry={nodes.barrel_barrel16_0003.geometry}
            material={materials["barrel16.003"]}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model005"
        position={[-7.9, 0, 7.02]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx005"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="barrel_metal_0005"
            castShadow
            receiveShadow
            geometry={nodes.barrel_metal_0005.geometry}
            material={materials["metal.005"]}
          />
          <mesh
            name="barrel_barrel16_0004"
            castShadow
            receiveShadow
            geometry={nodes.barrel_barrel16_0004.geometry}
            material={materials["barrel16.004"]}
          />
        </group>
      </group>
      <group name="Sketchfab_model006" rotation={[-Math.PI / 2, 0, 0]}>
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx006"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="boxes_barrel16_0001"
            castShadow
            receiveShadow
            geometry={nodes.boxes_barrel16_0001.geometry}
            material={materials["barrel16.005"]}
          />
        </group>
      </group>
      <group name="Sketchfab_model007" rotation={[-Math.PI / 2, 0, -2.83]}>
        <group
          name="68f1503f218a4d72ad4beaec9c1ffa12fbx007"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="boxes_boxes211_0001"
            castShadow
            receiveShadow
            geometry={nodes.boxes_boxes211_0001.geometry}
            material={materials["boxes211.001"]}
          />
          <mesh
            name="boxes_barrel16_0002"
            castShadow
            receiveShadow
            geometry={nodes.boxes_barrel16_0002.geometry}
            material={materials["barrel16.006"]}
          />
        </group>
      </group>
      <mesh
        name="viilage_sign"
        castShadow
        receiveShadow
        geometry={nodes.viilage_sign.geometry}
        material={materials["Material.002"]}
        position={[4.64, 0.15, 0.32]}
        rotation={[0, 1.55, 0]}
        scale={0.29}
      />
    </group>
  );
}

useGLTF.preload("/models/conts.gltf");
